<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Hyperparameter Tuning

## *Data Science Unit 4 Sprint 2 Assignment 4*

## Your Mission, should you choose to accept it...

To hyperparameter tune and extract every ounce of accuracy out of this telecom customer churn dataset: <https://lambdaschool-data-science.s3.amazonaws.com/telco-churn/WA_Fn-UseC_-Telco-Customer-Churn+(1).csv> 

## Requirements

- Load the data
- Clean the data if necessary (it will be)
- Create and fit a baseline Keras MLP model to the data.
- Hyperparameter tune (at least) the following parameters:
 - batch_size
 - training epochs
 - optimizer
 - learning rate (if applicable to optimizer)
 - momentum (if applicable to optimizer)
 - activation functions
 - network weight initialization
 - dropout regularization
 - number of neurons in the hidden layer
 
 You must use Grid Search and Cross Validation for your initial pass of the above hyperparameters
 
 Try and get the maximum accuracy possible out of this data! You'll save big telecoms millions! Doesn't that sound great?

In [66]:
import pandas as pd

data = pd.read_csv('https://lambdaschool-data-science.s3.amazonaws.com/telco-churn/WA_Fn-UseC_-Telco-Customer-Churn+(1).csv')

In [67]:
data.shape

(7043, 21)

In [68]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [80]:
#divide the data

y = data.loc[:, data.columns == 'Churn']
x = data.loc[:, data.columns != 'Churn']

In [83]:
#split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [8]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [8]:
for column in data.columns:
    print(column, data[column].isnull().sum())

customerID 0
gender 0
SeniorCitizen 0
Partner 0
Dependents 0
tenure 0
PhoneService 0
MultipleLines 0
InternetService 0
OnlineSecurity 0
OnlineBackup 0
DeviceProtection 0
TechSupport 0
StreamingTV 0
StreamingMovies 0
Contract 0
PaperlessBilling 0
PaymentMethod 0
MonthlyCharges 0
TotalCharges 0
Churn 0

In [9]:
for column in data.columns:
    print(column, (data[column] == 0).sum())

customerID 0
gender 0
SeniorCitizen 5901
Partner 0
Dependents 0
tenure 11
PhoneService 0
MultipleLines 0
InternetService 0
OnlineSecurity 0
OnlineBackup 0
DeviceProtection 0
TechSupport 0
StreamingTV 0
StreamingMovies 0
Contract 0
PaperlessBilling 0
PaymentMethod 0
MonthlyCharges 0
TotalCharges 0
Churn 0

In [10]:
for column in data.columns:
    print(column, data[column].dtype)

customerID object
gender object
SeniorCitizen int64
Partner object
Dependents object
tenure int64
PhoneService object
MultipleLines object
InternetService object
OnlineSecurity object
OnlineBackup object
DeviceProtection object
TechSupport object
StreamingTV object
StreamingMovies object
Contract object
PaperlessBilling object
PaymentMethod object
MonthlyCharges float64
TotalCharges object
Churn object

In [12]:
#replace all the yes/no with true/false

dict = {'Yes' : True, 'No': False}

for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = data[column].replace(dict)

In [86]:
#replace ALL the values

dict = {'Yes' : True, 'No': False}

for column in X_train.columns:
    if X_train[column].dtype == 'object':
        X_train[column] = X_train[column].replace(dict)
        
for column in X_test.columns:
    if X_test[column].dtype == 'object':
        X_test[column] = X_test[column].replace(dict)
        
for column in y_train.columns:
    if y_train[column].dtype == 'object':
        y_train[column] = y_train[column].replace(dict)
        
for column in y_test.columns:
    if y_test[column].dtype == 'object':
        y_test[column] = y_test[column].replace(dict)

C:\Users\Emma\.conda\envs\U4-S2-NN\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Emma\.conda\envs\U4-S2-NN\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Emma\.conda\envs\U4-S2-NN\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Emma\.conda\envs\U4-S2-NN\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [87]:
X_train.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
6607,7242-QZLXF,Male,0,False,True,1,False,No phone service,DSL,False,False,False,False,False,False,Month-to-month,True,Electronic check,25.30,25.3
2598,8325-QRPZR,Female,0,False,False,7,True,False,Fiber optic,False,False,True,False,False,False,Month-to-month,True,Electronic check,75.15,525
2345,7874-ECPQJ,Female,0,False,True,4,True,False,False,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,True,Bank transfer (automatic),20.05,85.5
4093,2476-YGEFM,Female,0,False,False,29,True,True,Fiber optic,False,False,False,False,False,False,Month-to-month,True,Credit card (automatic),76.00,2215.25
693,2276-YDAVZ,Female,0,False,False,3,True,True,Fiber optic,False,False,False,False,False,False,Month-to-month,True,Credit card (automatic),75.10,270.7

In [88]:
y_train.head()

      Churn
6607   True
2598  False
2345  False
4093  False
693    True

In [13]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,True,False,1,False,No phone service,DSL,False,...,False,False,False,False,Month-to-month,True,Electronic check,29.85,29.85,False
1,5575-GNVDE,Male,0,False,False,34,True,False,DSL,True,...,True,False,False,False,One year,False,Mailed check,56.95,1889.5,False
2,3668-QPYBK,Male,0,False,False,2,True,False,DSL,True,...,False,False,False,False,Month-to-month,True,Mailed check,53.85,108.15,True
3,7795-CFOCW,Male,0,False,False,45,False,No phone service,DSL,True,...,True,True,False,False,One year,False,Bank transfer (automatic),42.30,1840.75,False
4,9237-HQITU,Female,0,False,False,2,True,False,Fiber optic,False,...,False,False,False,False,Month-to-month,True,Electronic check,70.70,151.65,True

In [14]:
#it worked

for column in data.columns:
    print(column, data[column].dtype)

customerID object
gender object
SeniorCitizen int64
Partner bool
Dependents bool
tenure int64
PhoneService bool
MultipleLines object
InternetService object
OnlineSecurity object
OnlineBackup object
DeviceProtection object
TechSupport object
StreamingTV object
StreamingMovies object
Contract object
PaperlessBilling bool
PaymentMethod object
MonthlyCharges float64
TotalCharges object
Churn bool

In [22]:
for column in data.columns:
    if data[column].dtype != 'int64':
        print('Column: ', column, data[column].value_counts(), '\n')

Column:  customerID 2133-TSRRM    1
0080-EMYVY    1
2632-TACXW    1
6169-PPETC    1
0822-QGCXA    1
             ..
4816-LXZYW    1
1222-LRYKO    1
3160-TYXLT    1
1498-NHTLT    1
1400-MMYXY    1
Name: customerID, Length: 7043, dtype: int64

Column:  gender Male      3555
Female    3488
Name: gender, dtype: int64

Column:  Partner False    3641
True     3402
Name: Partner, dtype: int64

Column:  Dependents False    4933
True     2110
Name: Dependents, dtype: int64

Column:  PhoneService True     6361
False     682
Name: PhoneService, dtype: int64

Column:  MultipleLines False               3390
True                2971
No phone service     682
Name: MultipleLines, dtype: int64

Column:  InternetService Fiber optic    3096
DSL            2421
False          1526
Name: InternetService, dtype: int64

Column:  OnlineSecurity False                  3498
True                   2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

Column:  OnlineBackup False                  3088
True                   2429
No internet service    1526
Name: OnlineBackup, dtype: int64

Column:  DeviceProtection False                  3095
True                   2422
No internet service    1526
Name: DeviceProtection, dtype: int64

Column:  TechSupport False                  3473
True                   2044
No internet service    1526
Name: TechSupport, dtype: int64

Column:  StreamingTV False                  2810
True                   2707
No internet service    1526
Name: StreamingTV, dtype: int64

Column:  StreamingMovies False                  2785
True                   2732
No internet service    1526
Name: StreamingMovies, dtype: int64

Column:  Contract Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

Column:  PaperlessBilling True     4171
False    2872
Name: PaperlessBilling, dtype: int64

Column:  PaymentMethod Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: PaymentMethod, dtype: int64

Column:  MonthlyCharges 20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
114.75     1
103.60     1
113.40     1
57.65      1
113.30     1
Name: MonthlyCharges, Length: 1585, dtype: int64

Column:  TotalCharges            11
20.2       11
19.75       9
19.65       8
19.9        8
           ..
7349.35     1
6873.75     1
316.2       1
5012.1      1
7082.45     1
Name: TotalCharges, Length: 6531, dtype: int64

Column:  Churn False    5174
True     1869
Name: Churn, dtype: int64

In [89]:
#we don't need customers ids

data = data.drop('customerID', axis=1)
X_train = X_train.drop('customerID', axis=1)
X_test = X_test.drop('customerID', axis=1)

In [56]:
#the encoder would not work unless I put it in a pipeline!!! big mad this took me so long

from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(
    ce.OrdinalEncoder())

data = pipeline.fit_transform(data)

In [90]:
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(
    ce.OrdinalEncoder())

X_train = pipeline.fit_transform(X_train)

In [91]:
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(
    ce.OrdinalEncoder())

X_test = pipeline.fit_transform(X_test)

In [92]:
X_train.tail()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
3772,1,0,True,False,1,True,2,2,3,1,1,1,3,3,1,True,1,95.00,4968
5191,2,0,True,True,23,True,3,1,3,3,2,3,3,3,3,True,3,91.10,4969
5226,1,0,True,True,12,True,2,3,2,2,3,2,2,2,1,True,1,21.15,4970
5390,1,1,False,False,12,True,3,2,1,1,2,1,3,3,1,True,1,99.45,4971
860,1,0,False,False,26,True,2,3,2,2,3,2,2,2,2,False,3,19.80,4972

In [59]:
data.tail()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,2,0,True,True,24,True,3,1,2,2,2,2,2,2,2,True,2,84.80,6527,False
7039,1,0,True,True,72,True,3,2,1,1,2,1,2,2,2,True,4,103.20,6528,False
7040,1,0,True,True,11,False,1,1,2,2,1,1,1,1,1,True,1,29.60,6529,False
7041,2,1,True,False,4,True,3,2,1,2,1,1,1,1,1,True,2,74.40,6530,True
7042,2,0,False,False,66,True,2,2,2,2,2,2,2,2,3,True,3,105.65,6531,False

In [53]:
data.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [60]:
data.shape

(7043, 20)

In [50]:
#does not work!!!

from sklearn.preprocessing import OrdinalEncoder
import category_encoders as ce

encoder = ce.OrdinalEncoder()

for column in data.columns:
    if data[column].dtype == 'object':
  #      encoder = OrdinalEncoder([[column]])
        encoder.fit_transform(data[column])

#encoder.fit_transform(data)

KeyError: 'gender'

In [61]:
data.head(20)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,True,False,1,False,1,1,1,1,1,1,1,1,1,True,1,29.85,1,False
1,2,0,False,False,34,True,2,1,2,2,2,1,1,1,2,False,2,56.95,2,False
2,2,0,False,False,2,True,2,1,2,1,1,1,1,1,1,True,2,53.85,3,True
3,2,0,False,False,45,False,1,1,2,2,2,2,1,1,2,False,3,42.30,4,False
4,1,0,False,False,2,True,2,2,1,2,1,1,1,1,1,True,1,70.70,5,True
5,1,0,False,False,8,True,3,2,1,2,2,1,2,2,1,True,1,99.65,6,True
6,2,0,False,True,22,True,3,2,1,1,1,1,2,1,1,True,4,89.10,7,False
7,1,0,False,False,10,False,1,1,2,2,1,1,1,1,1,False,2,29.75,8,False
8,1,0,True,False,28,True,3,2,1,2,2,2,2,2,1,True,1,104.80,9,True
9,2,0,False,True,62,True,2,1,2,1,1,1,1,1,2,False,3,56.15,10,False
10,2,0,True,True,13,True,2,1,2,2,1,1,1,1,1,True,2,49.95,11,False
11,2,0,False,False,16,True,2,3,3,3,3,3,3,3,3,False,4,18.95,12,False
12,2,0,True,False,58,True,3,2,1,2,2,1,2,2,2,False,4,100.35,13,False
13,2,0,False,False,49,True,3,2,1,1,2,1,2,2,1,True,3,103.70,14,True
14,2,0,False,False,25,True,2,2,2,2,2,2,2,2,1,True,1,105.50,15,False
15,1,0,True,True,69,True,3,2,2,1,2,2,2,2,3,False,4,113.25,16,False
16,1,0,False,False,52,True,2,3,3,3,3,3,3,3,2,False,2,20.65,17,False
17,2,0,False,True,71,True,3,2,2,2,2,1,2,2,3,False,3,106.70,18,False
18,1,0,True,True,10,True,2,1,1,2,2,2,1,1,1,False,4,55.20,19,True
19,1,0,False,False,21,True,2,2,1,1,2,1,1,2,1,True,1,90.05,20,False

In [62]:
#and let us normalize 

from sklearn.preprocessing import Normalizer

norm = Normalizer()

data = norm.fit_transform(data)

In [64]:
data

array([[3.32223622e-02, 0.00000000e+00, 3.32223622e-02, ...,
        9.91687511e-01, 3.32223622e-02, 0.00000000e+00],
       [3.00275169e-02, 0.00000000e+00, 0.00000000e+00, ...,
        8.55033543e-01, 3.00275169e-02, 0.00000000e+00],
       [3.68929444e-02, 0.00000000e+00, 0.00000000e+00, ...,
        9.93342528e-01, 5.53394166e-02, 1.84464722e-02],
       ...,
       [1.53160985e-04, 0.00000000e+00, 1.53160985e-04, ...,
        4.53356515e-03, 9.99988070e-01, 0.00000000e+00],
       [3.06258649e-04, 1.53129325e-04, 1.53129325e-04, ...,
        1.13928218e-02, 9.99934490e-01, 1.53129325e-04],
       [3.06175927e-04, 0.00000000e+00, 0.00000000e+00, ...,
        1.61737433e-02, 9.99817489e-01, 0.00000000e+00]])

In [93]:
#and now lets normalize the right data sheesh

X_train = norm.fit_transform(X_train)

In [94]:
X_test = norm.transform(X_test)

In [103]:
y_train = norm.fit_transform(y_train)
y_test = norm.transform(y_test)

In [97]:
#last check before doing the real work

X_train[0]

array([0.03983969, 0.        , 0.03983969, 0.        , 0.03983969,
       0.        , 0.03983969, 0.03983969, 0.03983969, 0.03983969,
       0.03983969, 0.03983969, 0.03983969, 0.03983969, 0.03983969,
       0.03983969, 0.03983969, 0.98802429, 0.03983969])

In [98]:
X_test[0]

array([0.03983969, 0.        , 0.03983969, 0.        , 0.03983969,
       0.        , 0.03983969, 0.03983969, 0.03983969, 0.03983969,
       0.03983969, 0.03983969, 0.03983969, 0.03983969, 0.03983969,
       0.03983969, 0.03983969, 0.98802429, 0.03983969])

### done cleaning

- Create and fit a baseline Keras MLP model to the data.
- Hyperparameter tune (at least) the following parameters:
 - batch_size
 - training epochs
 - optimizer
 - learning rate (if applicable to optimizer)
 - momentum (if applicable to optimizer)
 - activation functions
 - network weight initialization
 - dropout regularization
 - number of neurons in the hidden layer
 
 You must use Grid Search and Cross Validation for your initial pass of the above hyperparameters

In [109]:
yes = (y_train == True).sum()
no = (y_train == False).sum()

yes / (yes+no)

print('yes', yes, 'no', no)

yes 1390 no 3892

In [106]:
#a basic model to get started, yes?

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

seed = 812

inputs = X_train.shape[1]
epochs = 30
batch_size = 200

model = Sequential()
model.add(Dense(30, activation = 'relu', input_shape=(inputs, )))
model.add(Dense(30, activation = 'relu'))
model.add(Dense(1))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train,
          validation_data=(X_test, y_test),
         epochs=epochs)
        # batch_size=batch_size)

Train on 5282 samples, validate on 1761 samples
Epoch 1/30
5282/5282 [==============================] - 1s 197us/sample - loss: 0.9324 - accuracy: 0.7368 - val_loss: 0.5543 - val_accuracy: 0.7280
Epoch 2/30
5282/5282 [==============================] - 0s 56us/sample - loss: 0.5588 - accuracy: 0.7378 - val_loss: 0.5295 - val_accuracy: 0.7348
Epoch 3/30
5282/5282 [==============================] - 0s 61us/sample - loss: 0.5496 - accuracy: 0.7387 - val_loss: 0.5099 - val_accuracy: 0.7445
Epoch 4/30
5282/5282 [==============================] - 0s 65us/sample - loss: 0.5402 - accuracy: 0.7393 - val_loss: 0.5151 - val_accuracy: 0.7439
Epoch 5/30
5282/5282 [==============================] - 0s 63us/sample - loss: 0.5363 - accuracy: 0.7412 - val_loss: 0.4883 - val_accuracy: 0.7479
Epoch 6/30
5282/5282 [==============================] - 0s 57us/sample - loss: 0.5313 - accuracy: 0.7429 - val_loss: 0.4946 - val_accuracy: 0.7496
Epoch 7/30
5282/5282 [==============================] - 0s 57us/sample - loss: 0.5326 - accuracy: 0.7444 - val_loss: 0.4937 - val_accuracy: 0.7541
Epoch 8/30
5282/5282 [==============================] - 0s 58us/sample - loss: 0.5208 - accuracy: 0.7442 - val_loss: 0.4882 - val_accuracy: 0.7535
Epoch 9/30
5282/5282 [==============================] - 0s 63us/sample - loss: 0.5156 - accuracy: 0.7467 - val_loss: 0.5087 - val_accuracy: 0.7547
Epoch 10/30
5282/5282 [==============================] - 0s 62us/sample - loss: 0.5167 - accuracy: 0.7473 - val_loss: 0.4822 - val_accuracy: 0.7604
Epoch 11/30
5282/5282 [==============================] - 0s 56us/sample - loss: 0.5112 - accuracy: 0.7512 - val_loss: 0.4779 - val_accuracy: 0.7694
Epoch 12/30
5282/5282 [==============================] - 0s 58us/sample - loss: 0.5048 - accuracy: 0.7533 - val_loss: 0.4829 - val_accuracy: 0.7689
Epoch 13/30
5282/5282 [==============================] - 0s 68us/sample - loss: 0.5026 - accuracy: 0.7529 - val_loss: 0.4741 - val_accuracy: 0.7734
Epoch 14/30
5282/5282 [==============================] - 0s 69us/sample - loss: 0.5025 - accuracy: 0.7527 - val_loss: 0.4703 - val_accuracy: 0.7751
Epoch 15/30
5282/5282 [==============================] - 0s 85us/sample - loss: 0.5030 - accuracy: 0.7544 - val_loss: 0.4746 - val_accuracy: 0.7836
Epoch 16/30
5282/5282 [==============================] - 0s 66us/sample - loss: 0.4995 - accuracy: 0.7565 - val_loss: 0.4712 - val_accuracy: 0.7672
Epoch 17/30
5282/5282 [==============================] - 0s 66us/sample - loss: 0.4982 - accuracy: 0.7573 - val_loss: 0.4692 - val_accuracy: 0.7768
Epoch 18/30
5282/5282 [==============================] - 0s 81us/sample - loss: 0.4935 - accuracy: 0.7569 - val_loss: 0.4737 - val_accuracy: 0.7791
Epoch 19/30
5282/5282 [==============================] - 0s 73us/sample - loss: 0.5137 - accuracy: 0.7503 - val_loss: 0.4878 - val_accuracy: 0.7416
Epoch 20/30
5282/5282 [==============================] - 0s 71us/sample - loss: 0.4973 - accuracy: 0.7514 - val_loss: 0.4679 - val_accuracy: 0.7746
Epoch 21/30
5282/5282 [==============================] - 1s 100us/sample - loss: 0.4961 - accuracy: 0.7537 - val_loss: 0.4731 - val_accuracy: 0.7717
Epoch 22/30
5282/5282 [==============================] - 0s 64us/sample - loss: 0.4890 - accuracy: 0.7556 - val_loss: 0.4714 - val_accuracy: 0.7734
Epoch 23/30
5282/5282 [==============================] - 0s 58us/sample - loss: 0.4895 - accuracy: 0.7573 - val_loss: 0.4686 - val_accuracy: 0.7797
Epoch 24/30
5282/5282 [==============================] - 0s 65us/sample - loss: 0.4948 - accuracy: 0.7598 - val_loss: 0.4866 - val_accuracy: 0.7706
Epoch 25/30
5282/5282 [==============================] - 0s 61us/sample - loss: 0.4906 - accuracy: 0.7603 - val_loss: 0.4837 - val_accuracy: 0.7694
Epoch 26/30
5282/5282 [==============================] - 0s 57us/sample - loss: 0.4841 - accuracy: 0.7582 - val_loss: 0.4720 - val_accuracy: 0.7785
Epoch 27/30
5282/5282 [==============================] - 0s 57us/sample - loss: 0.4881 - accuracy: 0.7601 - val_loss: 0.4698 - val_accuracy: 0.7797
Epoch 28/30
5282/5282 [==============================] - 0s 63us/sample - loss: 0.4837 - accuracy: 0.7626 - val_loss: 0.4722 - val_accuracy: 0.7740
Epoch 29/30
5282/5282 [==============================] - 0s 66us/sample - loss: 0.4800 - accuracy: 0.7588 - val_loss: 0.4774 - val_accuracy: 0.7763
Epoch 30/30
5282/5282 [==============================] - 0s 69us/sample - loss: 0.4817 - accuracy: 0.7605 - val_loss: 0.4755 - val_accuracy: 0.7802

In [ ]:
scores = model.evaluate(X_train, y_train)
print(model.metrics_names, scores)

'''
output was wayyy to long:

 - 0s 29us/sample - loss: 0.5484 - accuracy: 0.7615
['loss', 'accuracy'] [0.4769918417578527, 0.761454]

'''

In [ ]:
#I can't try all of these all at once without it getting weird

'''
 - batch_size  X
 - training epochs
 - optimizer X
 - learning rate (if applicable to optimizer)
 - momentum (if applicable to optimizer)
 - activation functions X
 - network weight initialization
 - dropout regularization
 - number of neurons in the hidden layer
 
'''

In [124]:
import numpy
import pandas as pd
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier


seed = 812
numpy.random.seed(seed)

#make model function because scikitlearn
def create_model(optimizer= 'adam', activation='relu'):
    # create model
    model = Sequential()
    model.add(Dense(30, input_dim=19, activation='relu'))
    model.add(Dense(30, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

model = KerasClassifier(build_fn=create_model, verbose=0)

param_grid = {'batch_size': [50, 100, 200, 300, 500, 700],
              'epochs': [20],
             'optimizer': ['adam', 'nadam', 'SGD'],
             'activation': ['softmax', 'relu', 'tanh', 'sigmoid']}


grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

#results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7597391843795777 using {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7497127771377563, Stdev: 0.013374585235793083 with: {'activation': 'softmax', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7508464574813842, Stdev: 0.016828340982625645 with: {'activation': 'softmax', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7551989316940307, Stdev: 0.020237588367985757 with: {'activation': 'softmax', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7417623400688171, Stdev: 0.01417566838350615 with: {'activation': 'softmax', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7485742568969727, Stdev: 0.023662163718183495 with: {'activation': 'softmax', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7459249019622802, Stdev: 0.020098549233997263 with: {'activation': 'softmax', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7393016576766968, Stdev: 0.013562886233415797 with: {'activation': 'softmax', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7379766225814819, Stdev: 0.012147424829099654 with: {'activation': 'softmax', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7381665468215942, Stdev: 0.013021344436723077 with: {'activation': 'softmax', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7385444521903992, Stdev: 0.012949754373024746 with: {'activation': 'softmax', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7375981926918029, Stdev: 0.012391247084982184 with: {'activation': 'softmax', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7358948945999145, Stdev: 0.011885499525715928 with: {'activation': 'softmax', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7381654739379883, Stdev: 0.013777080425757624 with: {'activation': 'softmax', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7377872347831727, Stdev: 0.012984729213130203 with: {'activation': 'softmax', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7379762649536132, Stdev: 0.013615551689297822 with: {'activation': 'softmax', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'softmax', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7370300054550171, Stdev: 0.01283643753788714 with: {'activation': 'softmax', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7370301842689514, Stdev: 0.012377671640892528 with: {'activation': 'softmax', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7491435289382935, Stdev: 0.015844352614360128 with: {'activation': 'relu', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7540639877319336, Stdev: 0.019029037629500156 with: {'activation': 'relu', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7540634512901306, Stdev: 0.021191135861451705 with: {'activation': 'relu', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.745924711227417, Stdev: 0.02122790240287744 with: {'activation': 'relu', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7502775549888611, Stdev: 0.02579524521783929 with: {'activation': 'relu', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7476278305053711, Stdev: 0.02335667679342456 with: {'activation': 'relu', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7385446190834045, Stdev: 0.012946989535314887 with: {'activation': 'relu', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7366524696350097, Stdev: 0.012079845084275167 with: {'activation': 'relu', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368414998054504, Stdev: 0.012094932906705998 with: {'activation': 'relu', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7358950734138489, Stdev: 0.011513628018305975 with: {'activation': 'relu', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7345707535743713, Stdev: 0.011929909083732202 with: {'activation': 'relu', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7375981926918029, Stdev: 0.012391247084982184 with: {'activation': 'relu', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7372195839881897, Stdev: 0.012608751947562289 with: {'activation': 'relu', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.736841332912445, Stdev: 0.011994327626841873 with: {'activation': 'relu', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7383546948432922, Stdev: 0.013947019340012832 with: {'activation': 'relu', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.737786865234375, Stdev: 0.013412531741000596 with: {'activation': 'relu', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7366517543792724, Stdev: 0.012744763716143099 with: {'activation': 'relu', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7372195839881897, Stdev: 0.012608751947562289 with: {'activation': 'relu', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7597391843795777, Stdev: 0.025900887395074575 with: {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7497113585472107, Stdev: 0.02088259152530945 with: {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7498996734619141, Stdev: 0.01869807809472417 with: {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7463033199310303, Stdev: 0.021044565374076445 with: {'activation': 'tanh', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7483850359916687, Stdev: 0.023339510519149714 with: {'activation': 'tanh', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.746113920211792, Stdev: 0.01881290750134518 with: {'activation': 'tanh', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7434638500213623, Stdev: 0.019456541514599468 with: {'activation': 'tanh', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7362740397453308, Stdev: 0.012063285352504408 with: {'activation': 'tanh', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7379767894744873, Stdev: 0.01205482039411795 with: {'activation': 'tanh', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368411421775818, Stdev: 0.011832518678826228 with: {'activation': 'tanh', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.737787401676178, Stdev: 0.01251713722105105 with: {'activation': 'tanh', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7374088048934937, Stdev: 0.012724063344848519 with: {'activation': 'tanh', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7353274345397949, Stdev: 0.012063290497340097 with: {'activation': 'tanh', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7377872347831727, Stdev: 0.012984729213130203 with: {'activation': 'tanh', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7372194051742553, Stdev: 0.012497983611406848 with: {'activation': 'tanh', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'tanh', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7370301842689514, Stdev: 0.012944312562776656 with: {'activation': 'tanh', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7366515755653381, Stdev: 0.01260681162393061 with: {'activation': 'tanh', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7553874254226685, Stdev: 0.0218968999362989 with: {'activation': 'sigmoid', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7586042523384094, Stdev: 0.024097449512741696 with: {'activation': 'sigmoid', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.749901807308197, Stdev: 0.014195842401844816 with: {'activation': 'sigmoid', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7463034987449646, Stdev: 0.02048148986728055 with: {'activation': 'sigmoid', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7447896003723145, Stdev: 0.0183378590146414 with: {'activation': 'sigmoid', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7472497582435608, Stdev: 0.021616955670968534 with: {'activation': 'sigmoid', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7396799087524414, Stdev: 0.013731684958370188 with: {'activation': 'sigmoid', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7345705628395081, Stdev: 0.011675546993656756 with: {'activation': 'sigmoid', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7379771590232849, Stdev: 0.01257188242835955 with: {'activation': 'sigmoid', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.737219762802124, Stdev: 0.012170892039819478 with: {'activation': 'sigmoid', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.737787401676178, Stdev: 0.01251713722105105 with: {'activation': 'sigmoid', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.737787401676178, Stdev: 0.01251713722105105 with: {'activation': 'sigmoid', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7370300173759461, Stdev: 0.013058082720798676 with: {'activation': 'sigmoid', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7379762649536132, Stdev: 0.013615551689297822 with: {'activation': 'sigmoid', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368409872055054, Stdev: 0.012499596562444511 with: {'activation': 'sigmoid', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7379762649536132, Stdev: 0.013615551689297822 with: {'activation': 'sigmoid', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'sigmoid', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'sigmoid', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}

In [125]:
#I want to try the same thing again, because I got a higher score with less layers

import numpy
import pandas as pd
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier


seed = 812
numpy.random.seed(seed)

#make model function because scikitlearn
def create_model(optimizer= 'adam', activation='relu'):
    # create model
    model = Sequential()
    model.add(Dense(30, input_dim=19, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

model = KerasClassifier(build_fn=create_model, verbose=0)

param_grid = {'batch_size': [50, 100, 200, 300, 500, 700],
              'epochs': [20],
             'optimizer': ['adam', 'nadam', 'SGD'],
             'activation': ['softmax', 'relu', 'tanh', 'sigmoid']}


grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

#results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7461132168769836 using {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7419501185417176, Stdev: 0.016771787229900015 with: {'activation': 'softmax', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7406259894371032, Stdev: 0.014552391763919868 with: {'activation': 'softmax', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7406259775161743, Stdev: 0.014808457941648591 with: {'activation': 'softmax', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.737408971786499, Stdev: 0.012275728664882458 with: {'activation': 'softmax', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7383550524711608, Stdev: 0.012953949483729448 with: {'activation': 'softmax', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7379766225814819, Stdev: 0.012653105114889278 with: {'activation': 'softmax', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7372194051742553, Stdev: 0.01305940530131815 with: {'activation': 'softmax', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7385442614555359, Stdev: 0.013118161627220837 with: {'activation': 'softmax', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.737787401676178, Stdev: 0.01251713722105105 with: {'activation': 'softmax', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7370301842689514, Stdev: 0.012944312562776656 with: {'activation': 'softmax', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7372194051742553, Stdev: 0.01305940530131815 with: {'activation': 'softmax', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7372195839881897, Stdev: 0.012608751947562289 with: {'activation': 'softmax', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7381652951240539, Stdev: 0.013754106928470958 with: {'activation': 'softmax', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'softmax', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'softmax', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'softmax', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'softmax', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'softmax', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7383550524711608, Stdev: 0.012402885807068437 with: {'activation': 'relu', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7411930799484253, Stdev: 0.01569815910534933 with: {'activation': 'relu', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.740436589717865, Stdev: 0.014209441887700125 with: {'activation': 'relu', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7375981926918029, Stdev: 0.012391247084982184 with: {'activation': 'relu', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7400579810142517, Stdev: 0.014719005619506283 with: {'activation': 'relu', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7375981926918029, Stdev: 0.012391247084982184 with: {'activation': 'relu', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7385440945625306, Stdev: 0.013617746603648256 with: {'activation': 'relu', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7377872347831727, Stdev: 0.012984729213130203 with: {'activation': 'relu', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7377872347831727, Stdev: 0.012984729213130203 with: {'activation': 'relu', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7372195839881897, Stdev: 0.012608751947562289 with: {'activation': 'relu', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7381652951240539, Stdev: 0.013754106928470958 with: {'activation': 'relu', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7381652951240539, Stdev: 0.013754106928470958 with: {'activation': 'relu', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.73797607421875, Stdev: 0.013579115479818172 with: {'activation': 'relu', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'relu', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.73797607421875, Stdev: 0.013579115479818172 with: {'activation': 'relu', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'relu', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'relu', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'relu', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7387336611747741, Stdev: 0.012918732904572397 with: {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7461132168769836, Stdev: 0.02259114674889481 with: {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7425183057785034, Stdev: 0.01765779001561079 with: {'activation': 'tanh', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7374088048934937, Stdev: 0.01239564186753371 with: {'activation': 'tanh', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7394903421401977, Stdev: 0.014063785495735576 with: {'activation': 'tanh', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7379766225814819, Stdev: 0.012653105114889278 with: {'activation': 'tanh', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7383546948432922, Stdev: 0.013947019340012832 with: {'activation': 'tanh', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7374088048934937, Stdev: 0.012724063344848519 with: {'activation': 'tanh', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7375980138778686, Stdev: 0.012849481531921902 with: {'activation': 'tanh', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7381654739379883, Stdev: 0.013777080425757624 with: {'activation': 'tanh', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7374086141586303, Stdev: 0.01318435158498957 with: {'activation': 'tanh', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7370300054550171, Stdev: 0.01283643753788714 with: {'activation': 'tanh', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'tanh', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'tanh', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.737786865234375, Stdev: 0.013412531741000596 with: {'activation': 'tanh', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'tanh', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'tanh', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'tanh', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7427069902420044, Stdev: 0.017558487221885452 with: {'activation': 'sigmoid', 'batch_size': 50, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7423289179801941, Stdev: 0.016693097403437128 with: {'activation': 'sigmoid', 'batch_size': 50, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7432746291160583, Stdev: 0.01842874326608169 with: {'activation': 'sigmoid', 'batch_size': 50, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7374091625213623, Stdev: 0.012184087623976594 with: {'activation': 'sigmoid', 'batch_size': 100, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7375981926918029, Stdev: 0.012391247084982184 with: {'activation': 'sigmoid', 'batch_size': 100, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7393011212348938, Stdev: 0.01385915937385939 with: {'activation': 'sigmoid', 'batch_size': 100, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368409752845764, Stdev: 0.012839353040983166 with: {'activation': 'sigmoid', 'batch_size': 200, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7385440945625306, Stdev: 0.013617746603648256 with: {'activation': 'sigmoid', 'batch_size': 200, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7383548736572265, Stdev: 0.013446311610287509 with: {'activation': 'sigmoid', 'batch_size': 200, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7370303750038147, Stdev: 0.012503841678473774 with: {'activation': 'sigmoid', 'batch_size': 300, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'sigmoid', 'batch_size': 300, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.73797607421875, Stdev: 0.013579115479818172 with: {'activation': 'sigmoid', 'batch_size': 300, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'sigmoid', 'batch_size': 500, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7366515755653381, Stdev: 0.01260681162393061 with: {'activation': 'sigmoid', 'batch_size': 500, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'sigmoid', 'batch_size': 500, 'epochs': 20, 'optimizer': 'SGD'}
Means: 0.7370300054550171, Stdev: 0.01283643753788714 with: {'activation': 'sigmoid', 'batch_size': 700, 'epochs': 20, 'optimizer': 'adam'}
Means: 0.7370300054550171, Stdev: 0.01283643753788714 with: {'activation': 'sigmoid', 'batch_size': 700, 'epochs': 20, 'optimizer': 'nadam'}
Means: 0.7368407845497131, Stdev: 0.012716509457793904 with: {'activation': 'sigmoid', 'batch_size': 700, 'epochs': 20, 'optimizer': 'SGD'}

In [ ]:
#now that I have a batch size, optimizer, and activattion selected, 
#I will grid search weight, dropout, neurons 
#the last thing will be epochs

import numpy
import pandas as pd
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier


seed = 812
numpy.random.seed(seed)

#make model function because scikitlearn
def create_model(init_mode = 'uniform', dropout_weight=0.0, weight_constraint=0.0, neurons=1):
    # create model
    model = Sequential()
    model.add(Dense(30, input_dim=19, activation='relu'))
    model.add(Dropout(dropout_weight))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

model = KerasClassifier(build_fn=create_model, verbose=0)

param_grid = {'init_mode': ['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform'],
              'epochs': [20],
             'dropout_weight': [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
             'weight_constraint': [1, 2, 3, 4, 5],
             'neurons': [5, 10, 20, 30, 50]}


grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

#results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

In [ ]:
wandb.init(project="ds10_inclass", entity="ds8") #Initializes and Experiment

# Important Hyperparameters
X =  x_train
y =  y_train

inputs = X.shape[1]
wandb.config.epochs = 50
wandb.config.batch_size = 10

# Create Model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(inputs,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))
# Compile Model
model.compile(optimizer='adam', loss='mse', metrics=['mse', 'mae'])

# Fit Model
model.fit(X, y, 
          validation_split=0.33, 
          epochs=wandb.config.epochs, 
          batch_size=wandb.config.batch_size, 
          callbacks=[WandbCallback()]
         )

## Stretch Goals:

- Try to implement Random Search Hyperparameter Tuning on this dataset
- Try to implement Bayesian Optimiation tuning on this dataset using hyperas or hyperopt (if you're brave)
- Practice hyperparameter tuning other datasets that we have looked at. How high can you get MNIST? Above 99%?
- Study for the Sprint Challenge
 - Can you implement both perceptron and MLP models from scratch with forward and backpropagation?
 - Can you implement both perceptron and MLP models in keras and tune their hyperparameters with cross validation?